/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_agenthandle_free: (a: number, b: number) => void;
export const __wbg_sessionstore_free: (a: number, b: number) => void;
export const agent_chat: (a: number, b: number, c: number, d: number) => any;
export const agenthandle_add_echo_tool: (a: number) => void;
export const agenthandle_add_js_tool: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => [number, number];
export const agenthandle_call_tool: (a: number, b: number, c: number, d: number, e: number) => any;
export const agenthandle_new: (a: number, b: number) => number;
export const agenthandle_run: (a: number, b: number, c: number) => any;
export const chat: (a: number, b: number, c: number, d: number) => any;
export const sessionstore_append_message: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const sessionstore_create: (a: number, b: number, c: number) => [number, number];
export const sessionstore_delete: (a: number, b: number, c: number) => [number, number];
export const sessionstore_get: (a: number, b: number, c: number) => [number, number, number, number];
export const sessionstore_list: (a: number) => [number, number];
export const sessionstore_new: () => number;
export const token_count: (a: number, b: number) => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h1214871e6dac7a9b: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5a7dad4203aed81f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__heffd7ef854a7947f: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__h4389e72fa9435afd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
